const workflows = [
    {
      id: "wf-legal-001",
      name: "Contract Lifecycle Guardian",
      description:
        "Automate the entire contract lifecycle from drafting to renewal with built-in compliance checks",
      category: "Legal",
      subcategory: "Contract Management",
      industry: "Legal",
      icon: "contract_guardian",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-15T08:00:00Z",
      lastUpdated: "2025-03-01T14:30:00Z",
      lastUsed: "2025-03-15T09:22:43Z",
      totalDocumentsProcessed: 438,
      averageProcessingTime: 45.2,
      successRate: 98.3,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "What aspects of the contract to focus on",
          type: "text",
          isRequired: true,
        },
        {
          name: "contractDocuments",
          description: "Contract documents to be analyzed",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "clauseExtraction",
        "obligationIdentification",
        "riskAssessment",
        "partyIdentification",
        "keyTermsExtraction",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 124,
      permissions: {
        roles: ["admin", "legal", "procurement"],
        featureAccess: "premium",
      },
      integrations: ["docusign", "salesforce", "microsoft365"],
      tags: ["contract", "legal", "compliance", "automation", "lifecycle"],
    },
    {
      id: "wf-legal-002",
      name: "Litigation Document Analyzer",
      description:
        "Extract key facts, precedents, and arguments from court filings and evidence",
      category: "Legal",
      subcategory: "Litigation",
      industry: "Legal",
      icon: "litigation_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-18T09:15:00Z",
      lastUpdated: "2025-02-27T16:10:00Z",
      lastUsed: "2025-03-14T14:37:22Z",
      totalDocumentsProcessed: 315,
      averageProcessingTime: 62.8,
      successRate: 96.7,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific aspects or arguments to focus on",
          type: "text",
          isRequired: true,
        },
        {
          name: "litigationDocuments",
          description: "Court filings and evidence documents",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "factExtraction",
        "precedentIdentification",
        "argumentAnalysis",
        "evidenceClassification",
        "timelineConstruction",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 86,
      permissions: {
        roles: ["admin", "legal", "paralegal"],
        featureAccess: "premium",
      },
      integrations: ["lexisnexis", "westlaw", "clio"],
      tags: ["litigation", "legal", "court", "case", "evidence"],
    },
    {
      id: "wf-legal-003",
      name: "Legal Discovery Accelerator",
      description:
        "Automatically identify and categorize responsive documents for discovery requests",
      category: "Legal",
      subcategory: "eDiscovery",
      industry: "Legal",
      icon: "ediscovery_accelerator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-22T11:30:00Z",
      lastUpdated: "2025-03-05T13:45:00Z",
      lastUsed: "2025-03-16T08:12:19Z",
      totalDocumentsProcessed: 1247,
      averageProcessingTime: 28.1,
      successRate: 97.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Discovery request parameters and search criteria",
          type: "text",
          isRequired: true,
        },
        {
          name: "documentCollection",
          description: "Document collection to search through",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "relevanceScoring",
        "privilegeDetection",
        "sensitiveInfoIdentification",
        "documentCategorization",
        "dataDeduplication",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 173,
      permissions: {
        roles: ["admin", "legal", "paralegal", "compliance"],
        featureAccess: "premium",
      },
      integrations: ["relativity", "concordance", "exterro"],
      tags: ["ediscovery", "legal", "discovery", "litigation", "responsive"],
    },
    {
      id: "wf-legal-004",
      name: "M&A Due Diligence Engine",
      description:
        "Identify potential risks and liabilities in acquisition target documentation",
      category: "Legal",
      subcategory: "Mergers & Acquisitions",
      industry: "Legal",
      icon: "ma_due_diligence",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-25T14:00:00Z",
      lastUpdated: "2025-03-08T09:30:00Z",
      lastUsed: "2025-03-15T16:47:33Z",
      totalDocumentsProcessed: 682,
      averageProcessingTime: 73.4,
      successRate: 98.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific risks or areas to focus on during the due diligence",
          type: "text",
          isRequired: true,
        },
        {
          name: "dueDiligenceDocuments",
          description: "Target company documentation for review",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "liabilityDetection",
        "contractRiskAssessment",
        "financialObligationExtraction",
        "complianceVerification",
        "assetValidation",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 92,
      permissions: {
        roles: ["admin", "legal", "finance", "executive"],
        featureAccess: "premium",
      },
      integrations: ["dealroom", "datasite", "intralinks"],
      tags: ["mergers", "acquisitions", "due diligence", "legal", "risk"],
    },
    {
      id: "wf-legal-005",
      name: "IP Portfolio Sentinel",
      description:
        "Track and analyze intellectual property assets, expirations, and potential infringements",
      category: "Legal",
      subcategory: "Intellectual Property",
      industry: "Legal",
      icon: "ip_sentinel",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-28T10:45:00Z",
      lastUpdated: "2025-03-10T11:20:00Z",
      lastUsed: "2025-03-17T09:53:11Z",
      totalDocumentsProcessed: 421,
      averageProcessingTime: 51.3,
      successRate: 97.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific IP concerns or monitoring requirements",
          type: "text",
          isRequired: true,
        },
        {
          name: "ipDocuments",
          description: "IP documentation and potentially infringing materials",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "patentAnalysis",
        "trademarkIdentification",
        "copyrightValidation",
        "infringementDetection",
        "expirationTracking",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 68,
      permissions: {
        roles: ["admin", "legal", "ip-specialist", "product"],
        featureAccess: "premium",
      },
      integrations: ["patentscope", "tmview", "clarivate"],
      tags: [
        "intellectual property",
        "patents",
        "trademarks",
        "legal",
        "infringement",
      ],
    },
    {
      id: "wf-legal-006",
      name: "Outside Counsel Fee Auditor",
      description:
        "Review legal invoices to ensure compliance with billing guidelines and identify savings opportunities",
      category: "Legal",
      subcategory: "Legal Operations",
      industry: "Legal",
      icon: "fee_auditor",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-30T15:20:00Z",
      lastUpdated: "2025-03-12T14:15:00Z",
      lastUsed: "2025-03-16T11:28:45Z",
      totalDocumentsProcessed: 594,
      averageProcessingTime: 32.6,
      successRate: 99.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific billing guidelines or concerns to focus on",
          type: "text",
          isRequired: true,
        },
        {
          name: "legalInvoices",
          description: "Outside counsel invoices to be audited",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "billingValidation",
        "rateComplianceCheck",
        "timeEntryAnalysis",
        "expenseVerification",
        "duplicateDetection",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 112,
      permissions: {
        roles: ["admin", "legal", "finance", "legal-ops"],
        featureAccess: "premium",
      },
      integrations: ["teamconnect", "brightflag", "quickbooks"],
      tags: [
        "legal operations",
        "billing",
        "invoices",
        "outside counsel",
        "cost control",
      ],
    },
    {
      id: "wf-legal-007",
      name: "Regulatory Change Monitor",
      description:
        "Track and assess the impact of new regulations on existing business practices and documents",
      category: "Legal",
      subcategory: "Regulatory Compliance",
      industry: "Legal",
      icon: "regulatory_monitor",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-03T08:45:00Z",
      lastUpdated: "2025-03-14T10:30:00Z",
      lastUsed: "2025-03-17T14:22:37Z",
      totalDocumentsProcessed: 329,
      averageProcessingTime: 56.7,
      successRate: 97.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific regulatory domains or changes to monitor",
          type: "text",
          isRequired: true,
        },
        {
          name: "businessDocuments",
          description: "Corporate documents to check against regulatory changes",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "regulatoryChangeDetection",
        "complianceGapAnalysis",
        "documentImpactAssessment",
        "remedyRecommendation",
        "implementationTracking",
      ],
      avgUserRating: 4.6,
      totalUserRatings: 83,
      permissions: {
        roles: ["admin", "legal", "compliance", "regulatory"],
        featureAccess: "premium",
      },
      integrations: ["thomson-reuters", "lexisnexis", "bloombergindustry"],
      tags: ["regulatory", "compliance", "legal", "change management", "risk"],
    },
    {
      id: "wf-legal-008",
      name: "Legal Research Synthesizer",
      description:
        "Extract relevant patterns and arguments from legal research documents",
      category: "Legal",
      subcategory: "Legal Research",
      industry: "Legal",
      icon: "research_synthesizer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-05T13:10:00Z",
      lastUpdated: "2025-03-16T09:45:00Z",
      lastUsed: "2025-03-17T16:08:54Z",
      totalDocumentsProcessed: 487,
      averageProcessingTime: 48.9,
      successRate: 98.4,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Legal question or issues to research",
          type: "text",
          isRequired: true,
        },
        {
          name: "researchDocuments",
          description:
            "Case law, statutes, articles, and other legal research materials",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "precedentExtraction",
        "argumentPatternRecognition",
        "statutoryInterpretation",
        "legalReasoningAnalysis",
        "counterargumentIdentification",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 97,
      permissions: {
        roles: ["admin", "legal", "paralegal", "researcher"],
        featureAccess: "premium",
      },
      integrations: ["westlaw", "lexisnexis", "heinonline"],
      tags: ["legal research", "case law", "precedent", "arguments", "synthesis"],
    },
    {
      id: "wf-legal-009",
      name: "Compliance Certificate Verifier",
      description:
        "Validate compliance certificates against current regulatory requirements",
      category: "Legal",
      subcategory: "Compliance",
      industry: "Legal",
      icon: "certificate_verifier",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-08T09:30:00Z",
      lastUpdated: "2025-03-17T08:15:00Z",
      lastUsed: "2025-03-17T13:42:21Z",
      totalDocumentsProcessed: 276,
      averageProcessingTime: 29.4,
      successRate: 99.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific compliance domains or certification requirements",
          type: "text",
          isRequired: true,
        },
        {
          name: "complianceCertificates",
          description: "Certificates and supporting documentation to verify",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "certificateAuthentication",
        "requirementValidation",
        "expirationTracking",
        "issuerVerification",
        "coverageAssessment",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 63,
      permissions: {
        roles: ["admin", "legal", "compliance", "procurement"],
        featureAccess: "premium",
      },
      integrations: ["navex", "sap", "aravo"],
      tags: [
        "compliance",
        "certificates",
        "verification",
        "regulatory",
        "validation",
      ],
    },
    {
      id: "wf-finance-010",
      name: "Loan Application Validator",
      description:
        "Verify loan documentation completeness and compliance with lending regulations",
      category: "Financial Services",
      subcategory: "Lending",
      industry: "Financial Services",
      icon: "loan_validator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-20T10:15:00Z",
      lastUpdated: "2025-02-28T11:45:00Z",
      lastUsed: "2025-03-16T13:42:18Z",
      totalDocumentsProcessed: 824,
      averageProcessingTime: 38.7,
      successRate: 97.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific validation requirements or regulatory focus",
          type: "text",
          isRequired: true,
        },
        {
          name: "loanDocuments",
          description: "Loan application documents to validate",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "documentCompleteness",
        "regulatoryCompliance",
        "informationConsistency",
        "fraudDetection",
        "requirementVerification",
      ],
      avgUserRating: 4.6,
      totalUserRatings: 87,
      permissions: {
        roles: ["admin", "financial-analyst", "loan-officer"],
        featureAccess: "premium",
      },
      integrations: ["quickbooks", "salesforce", "corebanking"],
      tags: ["loan", "finance", "validation", "compliance", "banking"],
    },
    {
      id: "wf-finance-011",
      name: "Investment Prospectus Analyzer",
      description:
        "Extract and summarize key terms, risks, and disclosures from investment documents",
      category: "Financial Services",
      subcategory: "Investment",
      industry: "Financial Services",
      icon: "prospectus_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-23T14:40:00Z",
      lastUpdated: "2025-03-02T16:35:00Z",
      lastUsed: "2025-03-17T10:18:42Z",
      totalDocumentsProcessed: 512,
      averageProcessingTime: 52.1,
      successRate: 98.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific investment concerns or focus areas",
          type: "text",
          isRequired: true,
        },
        {
          name: "investmentDocuments",
          description:
            "Prospectuses, offering memoranda, and other investment documents",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "riskFactorExtraction",
        "feeStructureAnalysis",
        "performanceClaimValidation",
        "disclosureIdentification",
        "investmentStrategyAnalysis",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 76,
      permissions: {
        roles: [
          "admin",
          "financial-analyst",
          "investment-advisor",
          "portfolio-manager",
        ],
        featureAccess: "premium",
      },
      integrations: ["bloomberg", "morningstar", "factset"],
      tags: ["investment", "prospectus", "finance", "risk", "disclosure"],
    },
    {
      id: "wf-finance-012",
      name: "Financial Statement Reconciler",
      description:
        "Compare financial documents for inconsistencies and potential reporting issues",
      category: "Financial Services",
      subcategory: "Accounting",
      industry: "Financial Services",
      icon: "statement_reconciler",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-26T09:25:00Z",
      lastUpdated: "2025-03-05T11:30:00Z",
      lastUsed: "2025-03-16T15:27:36Z",
      totalDocumentsProcessed: 673,
      averageProcessingTime: 43.5,
      successRate: 97.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific reconciliation goals or accounting concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "financialDocuments",
          description: "Financial statements and supporting documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "dataExtraction",
        "statementComparison",
        "discrepancyDetection",
        "trendAnalysis",
        "auditTrailConstruction",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 94,
      permissions: {
        roles: ["admin", "financial-analyst", "accountant", "auditor"],
        featureAccess: "premium",
      },
      integrations: ["quickbooks", "xero", "sap"],
      tags: [
        "finance",
        "reconciliation",
        "accounting",
        "audit",
        "financial statements",
      ],
    },
    {
      id: "wf-finance-013",
      name: "Fraud Pattern Detector",
      description:
        "Identify suspicious patterns in financial documentation indicating potential fraud",
      category: "Financial Services",
      subcategory: "Risk & Fraud",
      industry: "Financial Services",
      icon: "fraud_detector",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-29T11:15:00Z",
      lastUpdated: "2025-03-08T13:40:00Z",
      lastUsed: "2025-03-17T09:36:51Z",
      totalDocumentsProcessed: 942,
      averageProcessingTime: 57.2,
      successRate: 96.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific fraud concerns or patterns to detect",
          type: "text",
          isRequired: true,
        },
        {
          name: "financialDocuments",
          description: "Financial records and transaction documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "anomalyDetection",
        "patternRecognition",
        "historicalComparison",
        "irregularityScoring",
        "relationshipMapping",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 108,
      permissions: {
        roles: ["admin", "financial-analyst", "fraud-specialist", "risk-manager"],
        featureAccess: "premium",
      },
      integrations: ["splunk", "palantir", "sas"],
      tags: ["fraud", "finance", "detection", "risk", "compliance"],
    },
    {
      id: "wf-finance-014",
      name: "AML Documentation Screener",
      description:
        "Scan and validate KYC and anti-money laundering documentation",
      category: "Financial Services",
      subcategory: "Compliance",
      industry: "Financial Services",
      icon: "aml_screener",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-01T15:30:00Z",
      lastUpdated: "2025-03-10T14:15:00Z",
      lastUsed: "2025-03-17T11:43:27Z",
      totalDocumentsProcessed: 765,
      averageProcessingTime: 41.8,
      successRate: 98.7,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific AML compliance requirements or concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "kycDocuments",
          description: "KYC and customer documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "identityVerification",
        "sanctionsScreening",
        "pepsValidation",
        "documentAuthenticity",
        "riskScoring",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 82,
      permissions: {
        roles: ["admin", "compliance-officer", "risk-manager", "kyc-specialist"],
        featureAccess: "premium",
      },
      integrations: ["refinitiv", "lexisnexis", "dow-jones"],
      tags: ["aml", "kyc", "compliance", "finance", "screening"],
    },
    {
      id: "wf-finance-015",
      name: "ESG Compliance Evaluator",
      description:
        "Assess environmental, social, and governance compliance in corporate documentation",
      category: "Financial Services",
      subcategory: "ESG",
      industry: "Financial Services",
      icon: "esg_evaluator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-04T13:45:00Z",
      lastUpdated: "2025-03-12T10:30:00Z",
      lastUsed: "2025-03-16T14:23:09Z",
      totalDocumentsProcessed: 428,
      averageProcessingTime: 61.4,
      successRate: 97.3,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific ESG focus areas or rating framework",
          type: "text",
          isRequired: true,
        },
        {
          name: "corporateDocuments",
          description:
            "Corporate reports, disclosures, and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "environmentalMetricsExtraction",
        "socialImpactAssessment",
        "governancePracticeAnalysis",
        "sustainabilityClaimVerification",
        "frameworkAlignment",
      ],
      avgUserRating: 4.6,
      totalUserRatings: 71,
      permissions: {
        roles: [
          "admin",
          "esg-specialist",
          "compliance-officer",
          "investment-analyst",
        ],
        featureAccess: "premium",
      },
      integrations: ["msci", "sustainalytics", "bloomberg"],
      tags: ["esg", "sustainability", "compliance", "governance", "corporate"],
    },
    {
      id: "wf-finance-016",
      name: "Mortgage Document Verifier",
      description:
        "Ensure mortgage documentation is complete and compliant with lending regulations",
      category: "Financial Services",
      subcategory: "Mortgage",
      industry: "Financial Services",
      icon: "mortgage_verifier",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-07T09:10:00Z",
      lastUpdated: "2025-03-14T15:25:00Z",
      lastUsed: "2025-03-17T08:52:13Z",
      totalDocumentsProcessed: 731,
      averageProcessingTime: 46.2,
      successRate: 98.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific mortgage verification goals or regulatory focus",
          type: "text",
          isRequired: true,
        },
        {
          name: "mortgageDocuments",
          description: "Mortgage applications and supporting documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "documentCompleteness",
        "regulatoryCompliance",
        "informationConsistency",
        "riskAssessment",
        "disclosureValidation",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 89,
      permissions: {
        roles: [
          "admin",
          "mortgage-specialist",
          "compliance-officer",
          "underwriter",
        ],
        featureAccess: "premium",
      },
      integrations: ["ellie-mae", "black-knight", "fiserv"],
      tags: ["mortgage", "lending", "compliance", "verification", "real-estate"],
    },
    {
      id: "wf-finance-017",
      name: "Insurance Claim Validator",
      description:
        "Verify insurance claims against policy documents and identify discrepancies",
      category: "Financial Services",
      subcategory: "Insurance",
      industry: "Financial Services",
      icon: "claim_validator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-09T14:20:00Z",
      lastUpdated: "2025-03-15T09:35:00Z",
      lastUsed: "2025-03-17T13:17:44Z",
      totalDocumentsProcessed: 892,
      averageProcessingTime: 38.9,
      successRate: 97.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific claim validation requirements or concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "claimDocuments",
          description: "Insurance claims and policy documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "policyTermExtraction",
        "claimValidation",
        "coverageVerification",
        "exclusionIdentification",
        "fraudDetection",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 104,
      permissions: {
        roles: ["admin", "claims-adjuster", "underwriter", "fraud-investigator"],
        featureAccess: "premium",
      },
      integrations: ["guidewire", "duck-creek", "insurity"],
      tags: ["insurance", "claims", "validation", "policy", "verification"],
    },
    {
      id: "wf-finance-018",
      name: "Credit Risk Assessment Engine",
      description: "Analyze financial statements to evaluate credit risk metrics",
      category: "Financial Services",
      subcategory: "Credit Risk",
      industry: "Financial Services",
      icon: "credit_risk_engine",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-12T10:45:00Z",
      lastUpdated: "2025-03-16T12:25:00Z",
      lastUsed: "2025-03-17T15:36:28Z",
      totalDocumentsProcessed: 614,
      averageProcessingTime: 53.7,
      successRate: 97.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific credit risk metrics or concerns to focus on",
          type: "text",
          isRequired: true,
        },
        {
          name: "financialDocuments",
          description: "Financial statements and credit documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "financialRatioAnalysis",
        "cashflowEvaluation",
        "debtServiceCoverage",
        "collateralAssessment",
        "creditHistoryAnalysis",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 86,
      permissions: {
        roles: ["admin", "credit-analyst", "risk-manager", "loan-officer"],
        featureAccess: "premium",
      },
      integrations: ["experian", "equifax", "moodys"],
      tags: ["credit", "risk", "financial analysis", "lending", "assessment"],
    },
    {
      id: "wf-finance-019",
      name: "Earnings Call Sentiment Analyzer",
      description:
        "Extract and analyze sentiment and key financial indicators from earnings call transcripts",
      category: "Financial Services",
      subcategory: "Investor Relations",
      industry: "Financial Services",
      icon: "earnings_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-15T16:30:00Z",
      lastUpdated: "2025-03-17T09:45:00Z",
      lastUsed: "2025-03-17T16:12:35Z",
      totalDocumentsProcessed: 482,
      averageProcessingTime: 44.3,
      successRate: 96.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific sentiment or financial metrics to focus on",
          type: "text",
          isRequired: true,
        },
        {
          name: "earningsDocuments",
          description: "Earnings call transcripts and related materials",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "sentimentAnalysis",
        "keyMetricsExtraction",
        "forwardGuidanceIdentification",
        "competitiveInsightDetection",
        "trendTracking",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 73,
      permissions: {
        roles: [
          "admin",
          "financial-analyst",
          "investor-relations",
          "portfolio-manager",
        ],
        featureAccess: "premium",
      },
      integrations: ["factset", "bloomberg", "capitaliq"],
      tags: [
        "earnings",
        "sentiment",
        "financial analysis",
        "investor relations",
        "transcripts",
      ],
    },
    {
      id: "wf-healthcare-020",
      name: "HIPAA Compliance Guardian",
      description:
        "Automatically detect and flag protected health information in documents",
      category: "Healthcare",
      subcategory: "Compliance",
      industry: "Healthcare",
      icon: "hipaa_guardian",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-21T11:30:00Z",
      lastUpdated: "2025-03-01T13:15:00Z",
      lastUsed: "2025-03-17T10:28:43Z",
      totalDocumentsProcessed: 853,
      averageProcessingTime: 32.6,
      successRate: 99.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific PHI concerns or compliance requirements",
          type: "text",
          isRequired: true,
        },
        {
          name: "healthcareDocuments",
          description: "Documents to scan for PHI and HIPAA compliance",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "phiDetection",
        "redactionSuggestion",
        "complianceVerification",
        "riskAssessment",
        "breachPrevention",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 132,
      permissions: {
        roles: [
          "admin",
          "compliance-officer",
          "healthcare-provider",
          "privacy-officer",
        ],
        featureAccess: "premium",
      },
      integrations: ["epic", "cerner", "allscripts"],
      tags: ["hipaa", "healthcare", "compliance", "phi", "privacy"],
    },
    {
      id: "wf-healthcare-021",
      name: "Clinical Trial Protocol Analyzer",
      description:
        "Extract key requirements and procedures from clinical trial documentation",
      category: "Healthcare",
      subcategory: "Clinical Research",
      industry: "Healthcare",
      icon: "trial_protocol",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-24T14:45:00Z",
      lastUpdated: "2025-03-03T10:20:00Z",
      lastUsed: "2025-03-16T13:56:21Z",
      totalDocumentsProcessed: 487,
      averageProcessingTime: 57.4,
      successRate: 98.3,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific protocol elements or procedures to focus on",
          type: "text",
          isRequired: true,
        },
        {
          name: "trialDocuments",
          description: "Clinical trial protocols and supporting documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "inclusionExclusionExtraction",
        "endpointIdentification",
        "procedureMapping",
        "adverseEventDetection",
        "complianceVerification",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 79,
      permissions: {
        roles: [
          "admin",
          "clinical-researcher",
          "medical-director",
          "regulatory-affairs",
        ],
        featureAccess: "premium",
      },
      integrations: ["veeva", "medidata", "oracle-health-sciences"],
      tags: ["clinical trials", "protocols", "healthcare", "research", "medical"],
    },
    {
      id: "wf-healthcare-022",
      name: "Medical Coding Validator",
      description:
        "Review medical documentation to validate appropriate coding for billing",
      category: "Healthcare",
      subcategory: "Revenue Cycle",
      industry: "Healthcare",
      icon: "coding_validator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-27T09:30:00Z",
      lastUpdated: "2025-03-05T16:40:00Z",
      lastUsed: "2025-03-17T11:32:57Z",
      totalDocumentsProcessed: 924,
      averageProcessingTime: 41.8,
      successRate: 97.6,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific coding validation requirements or focus areas",
          type: "text",
          isRequired: true,
        },
        {
          name: "medicalDocuments",
          description: "Clinical documentation and coding information",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "diagnosisExtraction",
        "procedureIdentification",
        "codeValidation",
        "documentationSufficiency",
        "complianceVerification",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 116,
      permissions: {
        roles: [
          "admin",
          "medical-coder",
          "billing-specialist",
          "compliance-officer",
        ],
        featureAccess: "premium",
      },
      integrations: ["3m", "optum", "nuance"],
      tags: [
        "medical coding",
        "healthcare",
        "billing",
        "revenue cycle",
        "compliance",
      ],
    },
    {
      id: "wf-healthcare-023",
      name: "Patient Record Optimizer",
      description: "Analyze patient records for completeness and consistency",
      category: "Healthcare",
      subcategory: "Health Records",
      industry: "Healthcare",
      icon: "record_optimizer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-30T13:15:00Z",
      lastUpdated: "2025-03-08T09:20:00Z",
      lastUsed: "2025-03-17T14:27:36Z",
      totalDocumentsProcessed: 1157,
      averageProcessingTime: 36.5,
      successRate: 98.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific patient record optimization goals or concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "patientRecords",
          description: "Patient medical records and documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "recordCompleteness",
        "inconsistencyDetection",
        "missingInformationIdentification",
        "clinicalValidation",
        "documentationQuality",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 103,
      permissions: {
        roles: [
          "admin",
          "healthcare-provider",
          "medical-records",
          "quality-improvement",
        ],
        featureAccess: "premium",
      },
      integrations: ["epic", "cerner", "meditech"],
      tags: [
        "patient records",
        "healthcare",
        "optimization",
        "medical records",
        "documentation",
      ],
    },
    {
      id: "wf-healthcare-024",
      name: "Healthcare Provider Credentialing Verifier",
      description:
        "Validate healthcare provider credentials against requirements",
      category: "Healthcare",
      subcategory: "Credentialing",
      industry: "Healthcare",
      icon: "credential_verifier",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-02T10:45:00Z",
      lastUpdated: "2025-03-10T15:30:00Z",
      lastUsed: "2025-03-16T16:42:18Z",
      totalDocumentsProcessed: 621,
      averageProcessingTime: 42.7,
      successRate: 99.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific credentialing requirements or verification focus",
          type: "text",
          isRequired: true,
        },
        {
          name: "credentialDocuments",
          description: "Provider credentials and supporting documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "licenseVerification",
        "certificationValidation",
        "educationConfirmation",
        "privilegeAssessment",
        "expirationTracking",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 87,
      permissions: {
        roles: [
          "admin",
          "credentialing-specialist",
          "medical-staff-office",
          "compliance-officer",
        ],
        featureAccess: "premium",
      },
      integrations: ["caqh", "symplr", "verisys"],
      tags: [
        "credentialing",
        "healthcare",
        "provider",
        "verification",
        "compliance",
      ],
    },
    {
      id: "wf-healthcare-025",
      name: "Pharma Regulatory Submission Checker",
      description: "Ensure regulatory submissions meet all FDA/EMA requirements",
      category: "Healthcare",
      subcategory: "Pharmaceutical",
      industry: "Healthcare",
      icon: "regulatory_checker",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-05T15:20:00Z",
      lastUpdated: "2025-03-12T11:15:00Z",
      lastUsed: "2025-03-17T13:19:44Z",
      totalDocumentsProcessed: 543,
      averageProcessingTime: 68.3,
      successRate: 98.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific regulatory requirements or submission type",
          type: "text",
          isRequired: true,
        },
        {
          name: "regulatoryDocuments",
          description: "Regulatory submission documents and supporting materials",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "requirementValidation",
        "documentCompleteness",
        "consistencyVerification",
        "formatCompliance",
        "contentQualityAssessment",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 74,
      permissions: {
        roles: [
          "admin",
          "regulatory-affairs",
          "quality-assurance",
          "medical-affairs",
        ],
        featureAccess: "premium",
      },
      integrations: ["veeva", "documentum", "sparta-systems"],
      tags: ["regulatory", "pharmaceutical", "submission", "compliance", "fda"],
    },
    {
      id: "wf-healthcare-026",
      name: "Clinical Practice Guideline Mapper",
      description:
        "Compare patient treatment records against clinical guidelines",
      category: "Healthcare",
      subcategory: "Clinical Quality",
      industry: "Healthcare",
      icon: "guideline_mapper",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-08T09:40:00Z",
      lastUpdated: "2025-03-14T14:25:00Z",
      lastUsed: "2025-03-16T15:32:08Z",
      totalDocumentsProcessed: 472,
      averageProcessingTime: 54.6,
      successRate: 97.4,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific clinical guidelines or treatment protocols to evaluate",
          type: "text",
          isRequired: true,
        },
        {
          name: "clinicalDocuments",
          description: "Patient treatment records and clinical guidelines",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "guidelineExtraction",
        "treatmentMapping",
        "complianceAssessment",
        "varianceIdentification",
        "clinicalOutcomeAnalysis",
      ],
      avgUserRating: 4.6,
      totalUserRatings: 68,
      permissions: {
        roles: [
          "admin",
          "healthcare-provider",
          "clinical-quality",
          "medical-director",
        ],
        featureAccess: "premium",
      },
      integrations: ["epic", "cerner", "athenahealth"],
      tags: [
        "clinical guidelines",
        "healthcare",
        "treatment",
        "quality",
        "compliance",
      ],
    },
    {
      id: "wf-healthcare-027",
      name: "Medical Literature Knowledge Extractor",
      description:
        "Synthesize findings from clinical studies and medical literature",
      category: "Healthcare",
      subcategory: "Research",
      industry: "Healthcare",
      icon: "knowledge_extractor",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-11T13:50:00Z",
      lastUpdated: "2025-03-16T10:35:00Z",
      lastUsed: "2025-03-17T09:48:27Z",
      totalDocumentsProcessed: 789,
      averageProcessingTime: 63.2,
      successRate: 96.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific medical topics or research questions",
          type: "text",
          isRequired: true,
        },
        {
          name: "literatureDocuments",
          description: "Medical journals, studies, and research papers",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "keyFindingExtraction",
        "evidenceSynthesis",
        "methodologyAssessment",
        "outcomesAnalysis",
        "researchGapIdentification",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 91,
      permissions: {
        roles: ["admin", "researcher", "clinician", "medical-affairs"],
        featureAccess: "premium",
      },
      integrations: ["pubmed", "cochrane", "embase"],
      tags: [
        "medical literature",
        "research",
        "healthcare",
        "clinical studies",
        "evidence",
      ],
    },
    {
      id: "wf-healthcare-028",
      name: "Healthcare Supply Chain Contract Analyzer",
      description:
        "Identify pricing disparities and optimization opportunities in supply agreements",
      category: "Healthcare",
      subcategory: "Supply Chain",
      industry: "Healthcare",
      icon: "supply_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-14T11:25:00Z",
      lastUpdated: "2025-03-17T09:30:00Z",
      lastUsed: "2025-03-17T15:23:41Z",
      totalDocumentsProcessed: 524,
      averageProcessingTime: 49.7,
      successRate: 98.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific supply chain optimization goals or concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "supplyDocuments",
          description: "Supply contracts and purchasing documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "pricingExtraction",
        "termComparison",
        "volumeAnalysis",
        "discountIdentification",
        "savingsOpportunityDetection",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 76,
      permissions: {
        roles: ["admin", "supply-chain", "procurement", "finance"],
        featureAccess: "premium",
      },
      integrations: ["oracle", "sap", "infor"],
      tags: [
        "supply chain",
        "healthcare",
        "contracts",
        "procurement",
        "optimization",
      ],
    },
    {
      id: "wf-realestate-029",
      name: "Property Document Authenticator",
      description:
        "Verify authenticity and completeness of property documentation",
      category: "Real Estate",
      subcategory: "Documentation",
      industry: "Real Estate",
      icon: "document_authenticator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-22T13:20:00Z",
      lastUpdated: "2025-03-01T15:45:00Z",
      lastUsed: "2025-03-17T11:32:19Z",
      totalDocumentsProcessed: 693,
      averageProcessingTime: 43.8,
      successRate: 98.7,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific property document authentication requirements",
          type: "text",
          isRequired: true,
        },
        {
          name: "propertyDocuments",
          description: "Property documentation to authenticate",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "documentAuthenticity",
        "completenessVerification",
        "inconsistencyDetection",
        "signatureValidation",
        "tampering detection",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 82,
      permissions: {
        roles: ["admin", "real-estate-agent", "title-agent", "mortgage-officer"],
        featureAccess: "premium",
      },
      integrations: ["docusign", "zillow", "propertybase"],
      tags: [
        "real estate",
        "property",
        "authentication",
        "documentation",
        "verification",
      ],
    },
    {
      id: "wf-realestate-030",
      name: "Lease Agreement Optimizer",
      description:
        "Identify favorable and unfavorable terms in commercial and residential leases",
      category: "Real Estate",
      subcategory: "Leasing",
      industry: "Real Estate",
      icon: "lease_optimizer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-25T10:45:00Z",
      lastUpdated: "2025-03-04T13:30:00Z",
      lastUsed: "2025-03-16T16:27:43Z",
      totalDocumentsProcessed: 548,
      averageProcessingTime: 47.1,
      successRate: 97.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific lease optimization goals or concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "leaseDocuments",
          description: "Lease agreements and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "termExtraction",
        "conditionAnalysis",
        "favorabilityAssessment",
        "obligationIdentification",
        "comparisonToMarket",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 94,
      permissions: {
        roles: [
          "admin",
          "property-manager",
          "real-estate-agent",
          "leasing-agent",
        ],
        featureAccess: "premium",
      },
      integrations: ["appfolio", "buildium", "yardi"],
      tags: ["lease", "real estate", "optimization", "commercial", "residential"],
    },
    {
      id: "wf-realestate-031",
      name: "Title Defect Detector",
      description: "Flag potential title issues in property documentation",
      category: "Real Estate",
      subcategory: "Title",
      industry: "Real Estate",
      icon: "title_detector",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-28T15:10:00Z",
      lastUpdated: "2025-03-06T14:20:00Z",
      lastUsed: "2025-03-17T13:45:22Z",
      totalDocumentsProcessed: 726,
      averageProcessingTime: 51.3,
      successRate: 98.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific title concerns or issues to identify",
          type: "text",
          isRequired: true,
        },
        {
          name: "titleDocuments",
          description: "Property title and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "defectIdentification",
        "lienDetection",
        "easementDiscovery",
        "boundaryIssueSpotting",
        "ownershipVerification",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 89,
      permissions: {
        roles: ["admin", "title-agent", "real-estate-attorney", "escrow-officer"],
        featureAccess: "premium",
      },
      integrations: ["first-american", "old-republic", "stewart"],
      tags: ["title", "real estate", "defects", "property", "verification"],
    },
    {
      id: "wf-realestate-032",
      name: "Real Estate Due Diligence Accelerator",
      description:
        "Comprehensive assessment of property documentation during acquisitions",
      category: "Real Estate",
      subcategory: "Due Diligence",
      industry: "Real Estate",
      icon: "duediligence_accelerator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-31T09:40:00Z",
      lastUpdated: "2025-03-09T11:25:00Z",
      lastUsed: "2025-03-17T14:52:37Z",
      totalDocumentsProcessed: 842,
      averageProcessingTime: 68.7,
      successRate: 97.3,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific due diligence goals or concerns for the property",
          type: "text",
          isRequired: true,
        },
        {
          name: "propertyDocuments",
          description: "Property documentation for due diligence review",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "titleReview",
        "zoningAnalysis",
        "environmentalAssessment",
        "leaseSummary",
        "financialVerification",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 103,
      permissions: {
        roles: [
          "admin",
          "acquisition-specialist",
          "real-estate-investor",
          "property-manager",
        ],
        featureAccess: "premium",
      },
      integrations: ["costar", "realpage", "mri"],
      tags: [
        "due diligence",
        "real estate",
        "acquisition",
        "property",
        "assessment",
      ],
    },
    {
      id: "wf-realestate-033",
      name: "Zoning Compliance Analyzer",
      description: "Verify property usage against current zoning regulations",
      category: "Real Estate",
      subcategory: "Zoning",
      industry: "Real Estate",
      icon: "zoning_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-02T14:15:00Z",
      lastUpdated: "2025-03-10T15:30:00Z",
      lastUsed: "2025-03-16T12:17:44Z",
      totalDocumentsProcessed: 458,
      averageProcessingTime: 53.2,
      successRate: 97.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific zoning compliance concerns or requirements",
          type: "text",
          isRequired: true,
        },
        {
          name: "zoningDocuments",
          description: "Property and zoning documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "zoningClassificationExtraction",
        "usageComplianceVerification",
        "varianceIdentification",
        "restrictionAnalysis",
        "nonConformingUseDetection",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 68,
      permissions: {
        roles: [
          "admin",
          "real-estate-developer",
          "property-manager",
          "urban-planner",
        ],
        featureAccess: "premium",
      },
      integrations: ["esri", "mapbox", "propertyshark"],
      tags: ["zoning", "real estate", "compliance", "property", "regulations"],
    },
    {
      id: "wf-realestate-034",
      name: "Construction Contract Risk Assessor",
      description:
        "Identify potential liability and delay risks in construction contracts",
      category: "Real Estate",
      subcategory: "Construction",
      industry: "Real Estate",
      icon: "construction_assessor",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-05T10:30:00Z",
      lastUpdated: "2025-03-12T13:45:00Z",
      lastUsed: "2025-03-17T09:28:51Z",
      totalDocumentsProcessed: 376,
      averageProcessingTime: 57.4,
      successRate: 97.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific construction contract risks or concerns",
          type: "text",
          isRequired: true,
        },
        {
          name: "constructionDocuments",
          description: "Construction contracts and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "liabilityClauseIdentification",
        "delayRiskAssessment",
        "paymentTermAnalysis",
        "changeOrderEvaluation",
        "scopeCreepDetection",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 73,
      permissions: {
        roles: [
          "admin",
          "construction-manager",
          "real-estate-developer",
          "project-manager",
        ],
        featureAccess: "premium",
      },
      integrations: ["procore", "plangrid", "buildertrend"],
      tags: [
        "construction",
        "contracts",
        "real estate",
        "risk assessment",
        "liability",
      ],
    },
    {
      id: "wf-realestate-035",
      name: "Property Tax Assessment Validator",
      description:
        "Compare property tax assessments against comparable properties",
      category: "Real Estate",
      subcategory: "Property Tax",
      industry: "Real Estate",
      icon: "tax_validator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-08T16:20:00Z",
      lastUpdated: "2025-03-14T09:45:00Z",
      lastUsed: "2025-03-17T15:36:28Z",
      totalDocumentsProcessed: 521,
      averageProcessingTime: 41.9,
      successRate: 98.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific property tax assessment concerns or goals",
          type: "text",
          isRequired: true,
        },
        {
          name: "taxDocuments",
          description: "Property tax assessments and comparable property data",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "assessmentExtraction",
        "comparableAnalysis",
        "valulationDiscrepancyDetection",
        "taxRateVerification",
        "appealOpportunityIdentification",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 81,
      permissions: {
        roles: [
          "admin",
          "property-manager",
          "tax-consultant",
          "real-estate-investor",
        ],
        featureAccess: "premium",
      },
      integrations: ["corelogic", "blackknight", "realpage"],
      tags: [
        "property tax",
        "assessment",
        "real estate",
        "valuation",
        "comparison",
      ],
    },
    {
      id: "wf-realestate-036",
      name: "Tenant Screening Enhancer",
      description:
        "Analyze tenant applications and documentation for comprehensive risk assessment",
      category: "Real Estate",
      subcategory: "Property Management",
      industry: "Real Estate",
      icon: "tenant_screener",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-10T13:40:00Z",
      lastUpdated: "2025-03-15T14:10:00Z",
      lastUsed: "2025-03-17T10:48:52Z",
      totalDocumentsProcessed: 894,
      averageProcessingTime: 36.5,
      successRate: 98.7,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific tenant screening criteria or risks to assess",
          type: "text",
          isRequired: true,
        },
        {
          name: "tenantDocuments",
          description: "Tenant applications and supporting documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "incomeVerification",
        "employmentConfirmation",
        "creditHistoryAnalysis",
        "rentalHistoryAssessment",
        "riskScoring",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 97,
      permissions: {
        roles: ["admin", "property-manager", "leasing-agent", "landlord"],
        featureAccess: "premium",
      },
      integrations: ["appfolio", "buildium", "yardi"],
      tags: [
        "tenant screening",
        "real estate",
        "property management",
        "risk assessment",
        "leasing",
      ],
    },
    {
      id: "wf-hr-037",
      name: "Skills-to-Job Matchmaker",
      description:
        "Match candidate skills and experiences to job requirements with semantic understanding",
      category: "HR & Recruitment",
      subcategory: "Talent Acquisition",
      industry: "HR & Recruitment",
      icon: "skills_matchmaker",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-20T14:30:00Z",
      lastUpdated: "2025-03-02T09:15:00Z",
      lastUsed: "2025-03-17T13:27:42Z",
      totalDocumentsProcessed: 1042,
      averageProcessingTime: 42.3,
      successRate: 97.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific job requirements and skills matching criteria",
          type: "text",
          isRequired: true,
        },
        {
          name: "candidateDocuments",
          description: "Resumes and job descriptions to match",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "skillExtraction",
        "experienceMapping",
        "semanticMatching",
        "qualificationAssessment",
        "culturalFitAnalysis",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 126,
      permissions: {
        roles: ["admin", "recruiter", "hiring-manager", "hr-specialist"],
        featureAccess: "premium",
      },
      integrations: ["workday", "lever", "greenhouse"],
      tags: [
        "recruiting",
        "skills matching",
        "talent acquisition",
        "hr",
        "candidate assessment",
      ],
    },
    {
      id: "wf-hr-038",
      name: "HR Policy Compliance Checker",
      description:
        "Ensure HR policies align with current labor and employment regulations",
      category: "HR & Recruitment",
      subcategory: "Compliance",
      industry: "HR & Recruitment",
      icon: "policy_checker",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-23T09:45:00Z",
      lastUpdated: "2025-03-04T10:20:00Z",
      lastUsed: "2025-03-16T15:38:24Z",
      totalDocumentsProcessed: 683,
      averageProcessingTime: 48.7,
      successRate: 98.4,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific HR compliance requirements or jurisdictions",
          type: "text",
          isRequired: true,
        },
        {
          name: "policyDocuments",
          description: "HR policies and employment regulations",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "regulatoryComplianceCheck",
        "policyGapIdentification",
        "updateRecommendation",
        "jurisdictionalAnalysis",
        "riskAssessment",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 84,
      permissions: {
        roles: ["admin", "hr-manager", "compliance-officer", "legal"],
        featureAccess: "premium",
      },
      integrations: ["workday", "bamboohr", "adp"],
      tags: ["hr", "compliance", "policy", "employment law", "regulations"],
    },
    {
      id: "wf-hr-039",
      name: "Employee Documentation Verifier",
      description:
        "Validate completeness of employee documentation for compliance purposes",
      category: "HR & Recruitment",
      subcategory: "Document Management",
      industry: "HR & Recruitment",
      icon: "documentation_verifier",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-27T15:30:00Z",
      lastUpdated: "2025-03-05T16:40:00Z",
      lastUsed: "2025-03-17T09:42:18Z",
      totalDocumentsProcessed: 1247,
      averageProcessingTime: 35.4,
      successRate: 99.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific documentation requirements or compliance focus",
          type: "text",
          isRequired: true,
        },
        {
          name: "employeeDocuments",
          description: "Employee files and documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "documentCompletenessCheck",
        "signatureVerification",
        "expirationTracking",
        "inconsistencyDetection",
        "complianceValidation",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 103,
      permissions: {
        roles: [
          "admin",
          "hr-specialist",
          "compliance-officer",
          "document-manager",
        ],
        featureAccess: "premium",
      },
      integrations: ["workday", "bamboohr", "peoplesoft"],
      tags: [
        "hr",
        "documentation",
        "compliance",
        "employee records",
        "verification",
      ],
    },
    {
      id: "wf-hr-040",
      name: "Performance Review Sentiment Analyzer",
      description: "Extract key themes and sentiments from performance reviews",
      category: "HR & Recruitment",
      subcategory: "Performance Management",
      industry: "HR & Recruitment",
      icon: "review_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-30T11:20:00Z",
      lastUpdated: "2025-03-08T13:15:00Z",
      lastUsed: "2025-03-16T14:52:37Z",
      totalDocumentsProcessed: 876,
      averageProcessingTime: 41.2,
      successRate: 96.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific performance review themes or sentiments to analyze",
          type: "text",
          isRequired: true,
        },
        {
          name: "reviewDocuments",
          description: "Performance review documents",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "sentimentAnalysis",
        "themeExtraction",
        "feedbackPatternIdentification",
        "strengthWeaknessAssessment",
        "developmentOpportunityDetection",
      ],
      avgUserRating: 4.6,
      totalUserRatings: 91,
      permissions: {
        roles: ["admin", "hr-manager", "team-lead", "people-operations"],
        featureAccess: "premium",
      },
      integrations: ["workday", "lattice", "15five"],
      tags: [
        "performance reviews",
        "sentiment analysis",
        "hr",
        "feedback",
        "employee development",
      ],
    },
    {
      id: "wf-hr-041",
      name: "Compensation Equity Analyzer",
      description:
        "Identify potential compensation disparities across similar roles and qualifications",
      category: "HR & Recruitment",
      subcategory: "Compensation",
      industry: "HR & Recruitment",
      icon: "compensation_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-03T16:15:00Z",
      lastUpdated: "2025-03-10T14:45:00Z",
      lastUsed: "2025-03-17T11:24:53Z",
      totalDocumentsProcessed: 532,
      averageProcessingTime: 51.8,
      successRate: 97.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific compensation equity concerns or analysis goals",
          type: "text",
          isRequired: true,
        },
        {
          name: "compensationDocuments",
          description: "Compensation records and employee data",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "disparityDetection",
        "roleComparisonAnalysis",
        "qualificationAssessment",
        "marketBenchmarking",
        "equityRiskScoring",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 79,
      permissions: {
        roles: [
          "admin",
          "hr-director",
          "compensation-specialist",
          "diversity-officer",
        ],
        featureAccess: "premium",
      },
      integrations: ["workday", "adp", "payscale"],
      tags: ["compensation", "equity", "hr", "diversity", "pay analysis"],
    },
    {
      id: "wf-hr-042",
      name: "Workplace Investigation Document Manager",
      description:
        "Organize and analyze documentation related to workplace investigations",
      category: "HR & Recruitment",
      subcategory: "Employee Relations",
      industry: "HR & Recruitment",
      icon: "investigation_manager",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-06T13:30:00Z",
      lastUpdated: "2025-03-12T15:10:00Z",
      lastUsed: "2025-03-17T14:18:27Z",
      totalDocumentsProcessed: 468,
      averageProcessingTime: 54.3,
      successRate: 98.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific investigation focus or documentation needs",
          type: "text",
          isRequired: true,
        },
        {
          name: "investigationDocuments",
          description: "Workplace investigation documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "timelineConstruction",
        "statementAnalysis",
        "inconsistencyDetection",
        "policyViolationAssessment",
        "evidenceCategorization",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 67,
      permissions: {
        roles: ["admin", "hr-manager", "employee-relations", "legal"],
        featureAccess: "premium",
      },
      integrations: ["workday", "bamboohr", "relativity"],
      tags: [
        "workplace investigations",
        "hr",
        "employee relations",
        "documentation",
        "compliance",
      ],
    },
    {
      id: "wf-corporate-043",
      name: "Board Meeting Intelligence",
      description:
        "Extract key decisions, action items, and voting patterns from board documentation",
      category: "Corporate",
      subcategory: "Governance",
      industry: "Corporate",
      icon: "board_intelligence",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-21T15:45:00Z",
      lastUpdated: "2025-03-01T10:20:00Z",
      lastUsed: "2025-03-17T09:14:36Z",
      totalDocumentsProcessed: 428,
      averageProcessingTime: 47.6,
      successRate: 98.7,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific board meeting analysis goals or focus areas",
          type: "text",
          isRequired: true,
        },
        {
          name: "boardDocuments",
          description: "Board meeting minutes and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "decisionExtraction",
        "actionItemIdentification",
        "votingPatternAnalysis",
        "topicTrackingOverTime",
        "attendanceMonitoring",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 72,
      permissions: {
        roles: ["admin", "corporate-secretary", "board-member", "executive"],
        featureAccess: "premium",
      },
      integrations: ["diligent", "boardeffect", "boardvantage"],
      tags: [
        "board meetings",
        "corporate governance",
        "decision tracking",
        "action items",
        "minutes",
      ],
    },
    {
      id: "wf-corporate-044",
      name: "Strategic Initiative Tracker",
      description:
        "Monitor progress and alignment of initiatives through documentation analysis",
      category: "Corporate",
      subcategory: "Strategy",
      industry: "Corporate",
      icon: "initiative_tracker",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-24T11:20:00Z",
      lastUpdated: "2025-03-03T13:40:00Z",
      lastUsed: "2025-03-16T15:27:42Z",
      totalDocumentsProcessed: 614,
      averageProcessingTime: 52.8,
      successRate: 97.4,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific strategic initiatives or tracking requirements",
          type: "text",
          isRequired: true,
        },
        {
          name: "strategyDocuments",
          description: "Strategic plans and progress documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "initiativeExtraction",
        "progressTracking",
        "alignmentAssessment",
        "riskIdentification",
        "resourceAllocationAnalysis",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 83,
      permissions: {
        roles: ["admin", "executive", "project-manager", "strategy-analyst"],
        featureAccess: "premium",
      },
      integrations: ["smartsheet", "asana", "microsoft-project"],
      tags: [
        "strategic initiatives",
        "project tracking",
        "corporate strategy",
        "alignment",
        "monitoring",
      ],
    },
    {
      id: "wf-corporate-045",
      name: "Vendor Contract Consolidator",
      description: "Identify optimization opportunities across vendor agreements",
      category: "Corporate",
      subcategory: "Procurement",
      industry: "Corporate",
      icon: "contract_consolidator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-27T13:45:00Z",
      lastUpdated: "2025-03-05T09:30:00Z",
      lastUsed: "2025-03-17T11:48:23Z",
      totalDocumentsProcessed: 782,
      averageProcessingTime: 59.3,
      successRate: 98.1,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific vendor contract optimization goals or focus areas",
          type: "text",
          isRequired: true,
        },
        {
          name: "vendorDocuments",
          description: "Vendor contracts and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "termExtraction",
        "pricingAnalysis",
        "serviceOverlapIdentification",
        "savingsOpportunityDetection",
        "consolidationRecommendation",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 94,
      permissions: {
        roles: ["admin", "procurement", "finance", "legal"],
        featureAccess: "premium",
      },
      integrations: ["coupa", "sap-ariba", "oracle"],
      tags: [
        "vendor management",
        "contracts",
        "procurement",
        "optimization",
        "cost savings",
      ],
    },
    {
      id: "wf-corporate-046",
      name: "Corporate Governance Scorer",
      description:
        "Assess corporate governance quality based on documentation and disclosures",
      category: "Corporate",
      subcategory: "Governance",
      industry: "Corporate",
      icon: "governance_scorer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-01-31T14:10:00Z",
      lastUpdated: "2025-03-07T15:25:00Z",
      lastUsed: "2025-03-16T13:26:48Z",
      totalDocumentsProcessed: 539,
      averageProcessingTime: 63.7,
      successRate: 97.9,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific governance assessment criteria or frameworks",
          type: "text",
          isRequired: true,
        },
        {
          name: "governanceDocuments",
          description: "Corporate governance documents and disclosures",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "boardCompositionAnalysis",
        "disclosureQualityAssessment",
        "complianceVerification",
        "controlEvaluating",
        "stakeholderRightsAnalysis",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 76,
      permissions: {
        roles: [
          "admin",
          "corporate-secretary",
          "board-member",
          "compliance-officer",
        ],
        featureAccess: "premium",
      },
      integrations: ["diligent", "thomson-reuters", "bloomberg"],
      tags: [
        "corporate governance",
        "assessment",
        "board",
        "compliance",
        "disclosure",
      ],
    },
    {
      id: "wf-corporate-047",
      name: "Operational SOP Validator",
      description:
        "Ensure standard operating procedures are complete and aligned with regulations",
      category: "Corporate",
      subcategory: "Operations",
      industry: "Corporate",
      icon: "sop_validator",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-04T09:15:00Z",
      lastUpdated: "2025-03-09T14:30:00Z",
      lastUsed: "2025-03-17T10:52:39Z",
      totalDocumentsProcessed: 726,
      averageProcessingTime: 44.9,
      successRate: 98.5,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific SOP validation requirements or regulatory focus",
          type: "text",
          isRequired: true,
        },
        {
          name: "sopDocuments",
          description: "Standard operating procedures and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "completenessAssessment",
        "regulatoryAlignmentCheck",
        "inconsistencyDetection",
        "processGapIdentification",
        "improvementRecommendation",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 89,
      permissions: {
        roles: [
          "admin",
          "operations-manager",
          "process-engineer",
          "quality-assurance",
        ],
        featureAccess: "premium",
      },
      integrations: ["microsoft-sharepoint", "box", "docusign"],
      tags: [
        "standard operating procedures",
        "operations",
        "compliance",
        "process management",
        "validation",
      ],
    },
    {
      id: "wf-corporate-048",
      name: "Crisis Response Documentation Manager",
      description:
        "Organize and prioritize documentation during crisis situations",
      category: "Corporate",
      subcategory: "Risk Management",
      industry: "Corporate",
      icon: "crisis_manager",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-07T11:35:00Z",
      lastUpdated: "2025-03-11T16:20:00Z",
      lastUsed: "2025-03-17T15:27:36Z",
      totalDocumentsProcessed: 412,
      averageProcessingTime: 31.4,
      successRate: 99.2,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific crisis response documentation needs or priorities",
          type: "text",
          isRequired: true,
        },
        {
          name: "crisisDocuments",
          description: "Crisis documentation and communications",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "prioritizationAnalysis",
        "actionItemExtraction",
        "stakeholderImpactAssessment",
        "communicationConsistencyCheck",
        "decisionTrackingTimeline",
      ],
      avgUserRating: 4.9,
      totalUserRatings: 67,
      permissions: {
        roles: ["admin", "crisis-manager", "communications", "executive"],
        featureAccess: "premium",
      },
      integrations: ["everbridge", "servicenow", "microsoft-teams"],
      tags: [
        "crisis management",
        "emergency response",
        "documentation",
        "communications",
        "risk",
      ],
    },
    {
      id: "wf-corporate-049",
      name: "Supply Chain Risk Identifier",
      description:
        "Analyze vendor and supply chain documentation for potential disruption risks",
      category: "Corporate",
      subcategory: "Supply Chain",
      industry: "Corporate",
      icon: "supply_risk",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-10T14:25:00Z",
      lastUpdated: "2025-03-13T10:15:00Z",
      lastUsed: "2025-03-17T12:36:27Z",
      totalDocumentsProcessed: 673,
      averageProcessingTime: 57.8,
      successRate: 97.3,
      requiredInputs: [
        {
          name: "analysisObjective",
          description: "Specific supply chain risk concerns or focus areas",
          type: "text",
          isRequired: true,
        },
        {
          name: "supplyChainDocuments",
          description: "Vendor agreements and supply chain documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "disruptionRiskAssessment",
        "singleSourceDependencyDetection",
        "geopoliticalRiskAnalysis",
        "complianceVulnerabilityScanning",
        "contingencyPlanEvaluation",
      ],
      avgUserRating: 4.8,
      totalUserRatings: 84,
      permissions: {
        roles: ["admin", "supply-chain-manager", "procurement", "risk-manager"],
        featureAccess: "premium",
      },
      integrations: ["sap", "oracle", "riskmethods"],
      tags: [
        "supply chain",
        "risk management",
        "vendors",
        "disruption",
        "contingency planning",
      ],
    },
    {
      id: "wf-corporate-050",
      name: "Sustainability Report Analyzer",
      description:
        "Evaluate corporate sustainability documentation against reporting standards",
      category: "Corporate",
      subcategory: "ESG",
      industry: "Corporate",
      icon: "sustainability_analyzer",
      status: "inactive",
      isPublic: true,
      isCustomizable: true,
      createdAt: "2025-02-13T10:30:00Z",
      lastUpdated: "2025-03-15T15:40:00Z",
      lastUsed: "2025-03-17T14:18:42Z",
      totalDocumentsProcessed: 495,
      averageProcessingTime: 61.5,
      successRate: 97.8,
      requiredInputs: [
        {
          name: "analysisObjective",
          description:
            "Specific sustainability reporting standards or focus areas",
          type: "text",
          isRequired: true,
        },
        {
          name: "sustainabilityDocuments",
          description: "Sustainability reports and related documentation",
          type: "document",
          isRequired: true,
          maxCount: 20,
        },
      ],
      analysisModules: [
        "standardsComplianceCheck",
        "metricsExtractionAndVerification",
        "disclosureQualityAssessment",
        "benchmarkingAnalysis",
        "improvementOpportunityIdentification",
      ],
      avgUserRating: 4.7,
      totalUserRatings: 72,
      permissions: {
        roles: [
          "admin",
          "sustainability-officer",
          "esg-specialist",
          "corporate-communications",
        ],
        featureAccess: "premium",
      },
      integrations: ["bloomberg", "msci", "spglobal"],
      tags: [
        "sustainability",
        "esg",
        "reporting",
        "corporate responsibility",
        "standards",
      ],
    },
  ];
  
  export default workflows;
  